server:
  port: 8090
spring:
  application:
    name: "booking-service"
  datasource:
    url: jdbc:mysql://localhost:3306/carrentaldb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8888/"
#   rabbitmq:
#     host: "localhost"
#     port: 5672
#     username: "guest"
#     password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true
    
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
info:
  app:
    name: "booking-service"
    description: "Booking Service"
    version: "0.1.0"