server:
  port: 8888

spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
        #   search-locations: "classpath:/config"
        git:
          uri: "https://github.com/junwchoi85/car_rental_config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          username: "junwchoi85"
          password: "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"
#   rabbitmq:
#     host: "localhost"
#     port: 5672
#     username: "guest"
#     password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "FpSWLp7AG9LuV2NMCG2Yh3egmldaSXFh/9/aLOb1ykE="