server:
  port: 8400
spring:
  application:
    name: "user-service"
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental_app
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'app_admin'
    password: '1234'
  jpa:
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true
    
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
info:
  app:
    name: "user-service"
    description: "User Application"
    version: "0.1.0"

logging:
  level:
    io:
      classiccrew:
        user-service: DEBUG